In [1]:
import numpy as np

### Exercice 1:
Create a 1-dimensional NumPy array with 5 integers from 0 to 4.

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

 ### Exercice 2:
 Create a 2-dimensional NumPy array with shape (2, 3) containing only ones.

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### Exercice 3:
Create a 3-dimensional NumPy array with shape (2, 3, 4) containing only zeros.

In [4]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### Exercice 4:
Create a 2-dimensional NumPy array with shape (3, 4) containing random integers between 0 and 9.

In [5]:
np.random.randint(0,9,(3,4))

array([[3, 8, 6, 8],
       [0, 2, 3, 0],
       [6, 5, 8, 2]])

### Exercice 5:
Create a 2-dimensional NumPy array with shape (3, 4) and find its dimensions and size.

In [6]:
foo=np.random.randint(0,9,(3,4))
print(foo.shape, foo.ndim, foo.size)

(3, 4) 2 12


### Exercice 6:
Create a 2-dimensional NumPy array with shape (3, 4) and calculate the sum of all its elements.

In [7]:
foo=np.random.randint(0,9,(3,4))
print(foo, foo.sum())

[[6 2 0 0]
 [3 1 1 6]
 [8 7 6 7]] 47


### Exercice 7:
Create a 2-dimensional NumPy array with shape (3, 4) and find the minimum and maximum value in each row.

In [8]:
foo=np.random.randint(0,9,(3,4))
for i in range(4) : 
    print('colonne ', i, ':', np.min(foo[:,i]), np.max(foo[:,i]))
for i in range(3) :
    print('ligne ', i, ':', np.min(foo[i,:]), np.max(foo[i,:]))

colonne  0 : 0 6
colonne  1 : 3 8
colonne  2 : 6 6
colonne  3 : 3 7
ligne  0 : 6 7
ligne  1 : 3 8
ligne  2 : 0 6


In [9]:
# np.apply_over_axes(np.min, foo, 0)

### Exercice 8:
Create a 2-dimensional NumPy array with shape (3, 4) and replace all the odd numbers with -1.

In [10]:
foo=np.random.randint(0,9,(3,4))
foo[foo%2 == 1]=-1
print(foo)

[[ 0 -1  0 -1]
 [ 0  8  4 -1]
 [-1  0  6 -1]]


### Exercice 9:
Create a 2-dimensional NumPy array with shape (3, 4) and extract the elements in the second and third row and the second and third column.

In [11]:
foo=np.random.randint(0,9,(3,4))
bar=foo[1:3, 1:3]
print(foo, '\n', bar)

[[4 1 4 7]
 [6 1 4 5]
 [6 5 8 0]] 
 [[1 4]
 [5 8]]


### Exercice 10:
Create a 2-dimensional NumPy array with shape (3, 4) and multiply each element by 2.

In [12]:
foo=np.random.randint(0,9,(3,4))
bar=2*foo
print(foo, '\n', bar)

[[2 7 0 4]
 [5 7 7 7]
 [4 3 7 7]] 
 [[ 4 14  0  8]
 [10 14 14 14]
 [ 8  6 14 14]]
